---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: demo-app-sa  # Must have access to Secret Manager
      containers:
        - name: test-app
          image: asia-south1-docker.pkg.dev/gke-arena/preveen-repo/python-app:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: secrets-store
              mountPath: "/var/secrets"
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "demo-app-spc"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-app-spc
  namespace: app
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/gke-arena/secrets/MYSQL_DATABASE/versions/latest"
        path: "MYSQL_DATABASE"
      - resourceName: "projects/gke-arena/secrets/MYSQL_ROOT_PASSWORD/versions/latest"
        path: "MYSQL_ROOT_PASSWORD"
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace : app
spec:
  type: LoadBalancer
  ports:
  - name: test-service
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: test-app
---
